default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: asourrakh
  password: "Casanegra@1997"
  host: localhost

development:
  <<: *default
  database: bly_dev

test:
  <<: *default
  database: bly_test

production:
  <<: *default
  database: bly_prod
